### ISSUE TITLE
Improve LogstashJsonEventLayoutV1

### ISSUE THREAD

**Issue by gquintana** [vy/log4j2-logstash-layout#2]
Some ideas I wish log4j2-logstash-layout had:

* Rename `source_host` as `host` to be on par with Logstash Input File
* Be able to use environment variables, Java system properties in a layout template:
  * Use something like Log4J variable lookup to do property substitution https://logging.apache.org/log4j/2.0/manual/lookups.html
  * Be able to add context specific fields like: "environment": "production" (yet avoiding the use of MDC which makes things complicated).
* Filter MDC content: include only a subset of MDC fields
* Make field names shorter "exception.class" instead of "exception.exception_class", "thread" instead of "thread_name"

This could be done with a different "enhanced" layout template

**Comment by vy** [comment]
- Regarding *renaming* `source_host` to `host`, `exception.exception_class` to `exception.class`, and `thread_name` to `thread`, I intentionally picked those field names to be aligned with the official [logstash/log4j-jsonevent-layout](https://github.com/logstash/log4j-jsonevent-layout) project. (Am I missing something here?) In case of a particular need, you can provide your own JSON template.
- Providing an interface for variable substitution makes totally sense. I will check how can I do that.
- Extending MDC and NDC maps can be a little bit challenging given the lack of a proper JSON schema processor solution. What do you think of adding two new properties: `mdc_extension` and `ndc_extension`? I can merge these with `mdc` and `ndc` maps respectively prior to logging.
- About filtering MDC and NDC maps, would a simple `mdcKeyPattern` and `ndcKeyPattern` having a regex statement address your case? As you can imagine, these will definitely add quite some regex processing overhead to the logging too.

**Comment by vy** [comment]
- *Extending context*: From your description I understood that you just want to have a custom map similar to MDC/NDC. Right? If so, why not creating a map entry (i.e. `"ldc": {"foo": "bar", "baz": "moo"}`) in a custom JSON template? Am I misinterpreting your explanation?
- *Filtering MDC/NDC*: Do you want to filter on keys, values, or both?

**Comment by vy** [comment]
Just pushed v0.4 to Maven Central. Added `mdcKeyPattern` and `ndcPattern` configuration parameters. Further, Log4j 2.x Lookup support is integrated.

**Comment by gquintana** [comment]
Thanks. I'll reopen a new issue to be able to get environnement vars/system properties in template.

**Comment by vy** [comment]
@gquintana, I've already released that feature. Let me know if it doesn't work for you.
