### ISSUE TITLE
Pretty print when log level is error

### ISSUE THREAD

**Issue by sabareeshkkanan** [vy/log4j2-logstash-layout#30]
Well getting used to json log but it is really hard to read logs when there is error. Even though we are shipping it elastic search but it will be nice to have pretty print when the log level is error.

**Comment by vy** [comment]
I will think about it. (#28 and #29 are on the top of my TODO list right now.)

Just an idea: In your Log4j 2 configuration, you can create an additional file logger capturing only `error` level logs and formatting them via `PatternLayout`. Would that address your concern?

**Comment by sabareeshkkanan** [comment]
We solved this need by using traditional layout while doing local development
