### ISSUE TITLE
Ability to truncate individual fields

### ISSUE THREAD

**Issue by pmackles** [vy/log4j2-logstash-layout#31]
I think this is more of a feature request than a bug, but I am looking for a way to configure log4j2-logstash-layout so that it truncates certain fields if they are too long. It would be more granular than `maxByteCount` while also still allowing the message to go through. Something similar to the format modifiers in PatternLayout that allow you to truncate specific fields like `message` if it exceeds 10K characters. You can accomplish this through other means using logback but I can't find a way to do it in log4j2 short of a custom plugin.

If others agree with this, I can attempt a PR

**Comment by vy** [comment]
Seems like a legit request. The problem is, in addition to `message`, there are various places where this might be applicable such as `exception[Root]Cause:{message,className}`, `mdc`, `ndc`, etc. Further do we want it to be only enforced on dictionary values, or keys as well?

**Comment by vy** [comment]
After giving it some more thought, I am more inclined to delegate that responsibility to the application and have a hard bound (via `maxByteCount`) for protection in the logger. I feel like there are so many places where this limit can potentially be applied and abused. It is a matter of time people asking for "I would like to have a character limit on every field except this, this, and that ones", etc. I welcome some more thinking along though.

@pmackles, may I also assume that `log4j2-logstash-layout` is used in Adobe?

**Comment by pmackles** [comment]
@vy - I agree it would be something we want to be able to be able to apply to all fields without adding additional configuration properties for each individual field. 

I was thinking it could be defined somewhere in the layout template. Maybe an optional format modifier that can be applied to each lookup where the default is the current behavior? Or perhaps we can leverage the log4j2 plugin mechanism in some way? I looked at the latter for a few minutes but couldn't figure out how to apply it for this use case.

**Comment by vy** [comment]
@pmackles, I will not be available next week. The other week I will work on it -- a global character length limit on every key and val rendered.

**Comment by vy** [comment]
I am still thinking on what could be the best approach to this issue. I have consulted to [log4j-user](https://lists.apache.org/thread.html/7e31f539eba77bcdcba9385624337c7932711819972d510bbb0f42f8@%3Clog4j-user.logging.apache.org%3E) and [jackson-user](https://groups.google.com/d/msg/jackson-user/gRxvl6t80gs/Cvw2WrNVBgAJ) mailing lists with the hope to get some tips.

**Comment by vy** [comment]
@pmackles, would you mind commenting on the ac7f8f0 commit, please? If the changes address your need, I will cut a new release.

**Comment by vy** [comment]
@pmackles, v0.19 shipping these changes should appear momentarily on Maven Central. Enjoy!
