### ISSUE TITLE
Messages as json for Logger.log(Level, Object) support

### ISSUE THREAD

**Issue by gopalkakularam** [vy/log4j2-logstash-layout#36]
I am using Logger.log(Level, Object) and configured message as json:message:json in LogstashLayout. It only supports MultiformatMessage as json currently. Could you please provide support for any object as Json message as supported in JsonLayout of apache's log4j2 if we mention it as objectMessageAsJsonObject.

Also could you add support for the direct message should populated under messages instead of 
message : { message: { JsonObject }}

Should be like: message: {JsonObject}

**Comment by vy** [comment]
Hey @gopalkakularam! Sorry that this ticket has totally slipped through my inbox flood. (No, it definitely did not end up in the spam folder!) I will see what I can do.

**Comment by vy** [comment]
@gopalkakularam See the fix above. It addresses your requests. Let me know if they don't work for you. I will cut a new release in 1-2 days.
