### ISSUE TITLE
Environment variables,  system properties in template

### ISSUE THREAD

**Issue by gquintana** [vy/log4j2-logstash-layout#4]
Be able to use environment variables, Java system properties in a layout template...
Maybe use something like Log4J variable lookup to do property substitution https://logging.apache.org/log4j/2.0/manual/lookups.html

**Comment by vy** [comment]
Hey @gquintana, that feature is already released. Can you confirm if I dind't leave anything out? (You might want to use master branch, I will cut a new release in a couple of hours.)

**Comment by gquintana** [comment]
Awesome! Is it the same syntax as Log4J2?

**Comment by vy** [comment]
Yep! Exactly the same interpolator, with `${json:...}` extension.

**Comment by gquintana** [comment]
Sorry. Is it the same Lookup system: ${sys:user.name} ${env:USER} ?

**Comment by vy** [comment]
Both `${sys:user.name}` and `${env:USER}` do work on my system. There is no magic, it is the existing [Log4j 2 Lookups](https://logging.apache.org/log4j/2.0/manual/lookups.html) plus `{json:...}` extension.

**Comment by gquintana** [comment]
Thanks

**Comment by subhash982** [comment]
I tried the blow options but nothing is working for me. I have system property 'jobRunType' and tryinh to access using the below format in template. It is printing as it is with evaluating the expression. Can someone help if I am missing any thing ?

Template expression : 

  "JobRunType": "${json:sys:jobRunType}",
  "JobRunType1" :  "${json:jobRunType}",
  "JobRunType2" :  "${sys:jobRunTyp}"


Log Appender details,
        <Console name="console" target="SYSTEM_OUT">
            <LogstashLayout dateTimeFormatPattern="yyyy-MM-dd' 'HH:mm:ss,SSSZZ"
                            eventTemplateUri="classpath:log4j2-template.json"
                            prettyPrintEnabled="false"
                            stackTraceEnabled="true">
            </LogstashLayout>
        </Console>

**Comment by vy** [comment]
@subhash982, there is a typo in your template. `${sys:jobRunType}` should work, that is:

```json
{
  "JobRunType": "${sys:jobRunType}"
}
```
