### ISSUE TITLE
Custom user fields support

### ISSUE THREAD

**Issue by ov7a** [vy/log4j2-logstash-layout#43]
In the original logstash layout there is a possibility to use custom user fields:
https://github.com/logstash/log4j-jsonevent-layout#custom-user-fields
This feature is quite handy to provide, for example, a service name through log4j config.

I suppose one can do it with this lib, but It would require to use custom layout for each service which adds extra field with different value for each service. (Or maybe I didn't understand the docs). This way is not very convenient.

**Comment by vy** [comment]
Would the following approach work for you?

1. Add a `SERVICE_NAME` environment variable.
2. Copy `LogstashJsonEventLayoutV1.json` template from `log4j2-logstash-layout` classpath to your project with the name `CustomEventLayout.json` and append a `"serviceName": "${env:SERVICE_NAME}"` entry there.
3. Use `CustomEventLayout.json` template in the `LogstashLayout` entry of your Log4j config.

At [bol.com](https://bol.com), this is more or less what we do. An artifact wrapping `log4j2-logstash-layout` ships a custom template and the rest of the services just inject this wrapper artifact with certain properties.

**Comment by ov7a** [comment]
Thanks for the quick reply!

The approach you proposed is indeed more convenient in terms of less clunky configuration. However in requires more devops work: custom artifact and its distribution. That’s totally doable but not very convenient in heterogeneous environments with different templates or different types of distributions (regular/fatjar/appserver/etc).

I think adding custom fields feature has some advantages over your approach:
1. Configuration is more flexible and does not require custom template as artifact. Changing config is easier than changing a jar. Temporary changes are much easier.
2. Migration from the original logstash-layout is easier.

**Comment by vy** [comment]
Hrm... I see your point. Given your concern is to ease migration, do you have any strong preferences for the way you configure the additional fields? For instance, this is the `log4j-jsoneven-layout` configuration:

```xml
<param name="UserFields" value="foo:bar,baz:quz" />
```

And this is the Log4j 2 `JsonLayout` configuration:

```xml
<KeyValuePair key="additionalField1" value="constant value"/>
<KeyValuePair key="additionalField2" value="$${ctx:key}"/>
```

I personally prefer the latter, which is the common key-value configuration convention in Log4j 2.

**Comment by ov7a** [comment]
Either way is ok for me, but I think that the latter is more clear.

**Comment by vy** [comment]
I will try implementing this in 1-2 weeks. Is that good/quick enough for you?

**Comment by ov7a** [comment]
Yeah, thats great! Thank you very much!

**Comment by vy** [comment]
@ov7a If you (or your company) happens to be interested in donating bucks for this feature, feel free to ping me.

**Comment by vy** [comment]
@ov7a Would you mind checking if the recent fix addresses your problem, please?
