### ISSUE TITLE
No new lines after some time

### ISSUE THREAD

**Issue by greendale1924** [vy/log4j2-logstash-layout#6]
Hi,
Using this configuration
`   
 <Console name="Console" target="SYSTEM_OUT">
	    <LogstashLayout dateTimeFormatPattern="yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
	               templateUri="classpath:LogstashJsonEventLayoutV1.json"
	               prettyPrintEnabled="false"
	               stackTraceEnabled="true"
	               timeZoneId="TimeZone.GMT_ID"
	               />
    </Console>`

everything works as expected for the first several hundreds of lines: that is, one log message is printed per line (start and end with { and }).

After that it happens that one new line is omitted: so, two messages appear at a single line. After several more lines, new lines are not printed anymore and everything is appended to the last line of the log:

`...ger"}{"@version":1,...`

Any idea if it is a bug, or if I can work around it somehow?

**Comment by vy** [comment]
@greendale1924, I am assuming you're running the latest version -- 0.8 as of now. I suspect a regression related with concurrency in `JacksonNewlineAddingPrettyPrinter`. I will try to take a look at it in a couple of days. In the meantime, any hints that you can provide are more than welcome.

**Comment by greendale1924** [comment]
log4j2-logstash-layout - 0.8
log4j-* - 2.9.1
jackson-* - 2.8.3 (same problem with 2.8.10)

**Comment by vy** [comment]
@greendale1924, I've just pushed a fix. Would you mind checking if it fixes your case, please?

**Comment by greendale1924** [comment]
Thanks for the fix!
I can confirm that the described problem does not seem to appear with the latest code (0.9-SNAPSHOT).

Please note, that I could not build the whole project because of:
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.0.0:shade (default) on project log4j2-logstash-layout-fatjar: Error creating shaded jar: duplicate entry: META-INF/services/com.vlkan.log4j2.logstash.layout.jackson.core.ObjectCodec -> [Help 1]

but I only used log4j2-logstash-layout, so it was not a problem for me.

**Comment by vy** [comment]
Great to hear! Thanks for testing @greendale1924. Release 0.9 should appear in Maven Central momentarily.
