### ISSUE TITLE
extract certain MDC fields

### ISSUE THREAD

**Issue by hadjiski** [vy/log4j2-logstash-layout#7]
instead of having `{
  "mdc" : {
    "customThreadContextField" : "someValue1",
    "secondCustomThreadContextField" : "someValue2",
  },
  "@version" : 1,
  "source_host" : "raspberrypi",
  "message" : "some msg",
}`

I would like to have the mdc flat to the rest of the fields `{
  "customThreadContextField" : "someValue1",
  "secondCustomThreadContextField" : "someValue2",
  "@version" : 1,
  "source_host" : "raspberrypi",
  "message" : "some msg",
}`

Is that somehow possible? I tried adding `"customThreadContextField": "${mdc:customThreadContextField}",` to a custom layout template, but the syntax is obviously wrong.

**Comment by vy** [comment]
Unfortunately that (field unwrapping) is not supported at the moment. Such a feature would imply other intrinsic problems: What if the unwrapped fields conflict with the existing ones? How one shall determine the precedence?

**Comment by hadjiski** [comment]
well, in case of a conflict, throwing an exception seems to be valid

**Comment by vy** [comment]
Would you mind sharing your use case? Do you need all fields to be unwrapped or just a certain subset?

**Comment by hadjiski** [comment]
All should be enough, if subset is configurable, even better. Usecase is pretty simple: when things like session id, user id or something similar is to be logged with every log statement, I don't want to pass then to all my methods just to be able to log them, that's why they go to the ThreadContext, but still I consider them as flat to the rest of the fields.

**Comment by vy** [comment]
I think supporting a subset would be a more feasible solution to this problem. For instance, what if you could have just said `"sessionId": "${json:mdc:sessionId}"` in the template. Right?

**Comment by hadjiski** [comment]
sounds good

**Comment by vy** [comment]
@hadjiski, would you mind checking (and preferably testing) the just pushed commit whether it is addressing your concern or not, please?

**Comment by hadjiski** [comment]
@vy would work for me, thanks

**Comment by vy** [comment]
@hadjiski, I've pushed the new v0.10 release to Maven Central. Should be accessible soon. FYI.
